/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentLifeRouteImport } from './routes/student-life'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MediaRouteImport } from './routes/media'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as AdmissionsIndexRouteImport } from './routes/admissions.index'
import { Route as PortalStudentRouteImport } from './routes/portal.student'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ApplySuccessRouteImport } from './routes/apply.success'
import { Route as AdmissionsCheckStatusRouteImport } from './routes/admissions.check-status'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as PortalStudentLoginRouteImport } from './routes/portal.student_.login'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin.news'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminInquiriesRouteImport } from './routes/_authenticated/admin.inquiries'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'

const StudentLifeRoute = StudentLifeRouteImport.update({
  id: '/student-life',
  path: '/student-life',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyRoute,
} as any)
const AdmissionsIndexRoute = AdmissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdmissionsRoute,
} as any)
const PortalStudentRoute = PortalStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => PortalRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ApplySuccessRoute = ApplySuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ApplyRoute,
} as any)
const AdmissionsCheckStatusRoute = AdmissionsCheckStatusRouteImport.update({
  id: '/check-status',
  path: '/check-status',
  getParentRoute: () => AdmissionsRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const PortalStudentLoginRoute = PortalStudentLoginRouteImport.update({
  id: '/student_/login',
  path: '/student/login',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInquiriesRoute =
  AuthenticatedAdminInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRouteWithChildren
  '/alumni': typeof AlumniRoute
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/staff': typeof StaffRoute
  '/student-life': typeof StudentLifeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admissions/check-status': typeof AdmissionsCheckStatusRoute
  '/apply/success': typeof ApplySuccessRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portal/student': typeof PortalStudentRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/news/': typeof NewsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/portal/student/login': typeof PortalStudentLoginRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/alumni': typeof AlumniRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/media': typeof MediaRoute
  '/staff': typeof StaffRoute
  '/student-life': typeof StudentLifeRoute
  '/admissions/check-status': typeof AdmissionsCheckStatusRoute
  '/apply/success': typeof ApplySuccessRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portal/student': typeof PortalStudentRoute
  '/admissions': typeof AdmissionsIndexRoute
  '/apply': typeof ApplyIndexRoute
  '/news': typeof NewsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/portal/student/login': typeof PortalStudentLoginRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRouteWithChildren
  '/alumni': typeof AlumniRoute
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/staff': typeof StaffRoute
  '/student-life': typeof StudentLifeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admissions/check-status': typeof AdmissionsCheckStatusRoute
  '/apply/success': typeof ApplySuccessRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portal/student': typeof PortalStudentRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/news/': typeof NewsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/portal/student_/login': typeof PortalStudentLoginRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/alumni'
    | '/apply'
    | '/auth'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/media'
    | '/news'
    | '/portal'
    | '/staff'
    | '/student-life'
    | '/admin'
    | '/admissions/check-status'
    | '/apply/success'
    | '/news/$slug'
    | '/portal/student'
    | '/admissions/'
    | '/apply/'
    | '/news/'
    | '/portal/'
    | '/admin/applications'
    | '/admin/events'
    | '/admin/inquiries'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/news'
    | '/portal/student/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/alumni'
    | '/auth'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/media'
    | '/staff'
    | '/student-life'
    | '/admissions/check-status'
    | '/apply/success'
    | '/news/$slug'
    | '/portal/student'
    | '/admissions'
    | '/apply'
    | '/news'
    | '/portal'
    | '/admin/applications'
    | '/admin/events'
    | '/admin/inquiries'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/news'
    | '/portal/student/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/alumni'
    | '/apply'
    | '/auth'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/media'
    | '/news'
    | '/portal'
    | '/staff'
    | '/student-life'
    | '/_authenticated/admin'
    | '/admissions/check-status'
    | '/apply/success'
    | '/news/$slug'
    | '/portal/student'
    | '/admissions/'
    | '/apply/'
    | '/news/'
    | '/portal/'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/inquiries'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/news'
    | '/portal/student_/login'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRouteWithChildren
  AlumniRoute: typeof AlumniRoute
  ApplyRoute: typeof ApplyRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  MediaRoute: typeof MediaRoute
  NewsRoute: typeof NewsRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  StaffRoute: typeof StaffRoute
  StudentLifeRoute: typeof StudentLifeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-life': {
      id: '/student-life'
      path: '/student-life'
      fullPath: '/student-life'
      preLoaderRoute: typeof StudentLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/apply/': {
      id: '/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/admissions/': {
      id: '/admissions/'
      path: '/'
      fullPath: '/admissions/'
      preLoaderRoute: typeof AdmissionsIndexRouteImport
      parentRoute: typeof AdmissionsRoute
    }
    '/portal/student': {
      id: '/portal/student'
      path: '/student'
      fullPath: '/portal/student'
      preLoaderRoute: typeof PortalStudentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/apply/success': {
      id: '/apply/success'
      path: '/success'
      fullPath: '/apply/success'
      preLoaderRoute: typeof ApplySuccessRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/admissions/check-status': {
      id: '/admissions/check-status'
      path: '/check-status'
      fullPath: '/admissions/check-status'
      preLoaderRoute: typeof AdmissionsCheckStatusRouteImport
      parentRoute: typeof AdmissionsRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/portal/student_/login': {
      id: '/portal/student_/login'
      path: '/student/login'
      fullPath: '/portal/student/login'
      preLoaderRoute: typeof PortalStudentLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inquiries': {
      id: '/_authenticated/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AuthenticatedAdminInquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminInquiriesRoute: typeof AuthenticatedAdminInquiriesRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminInquiriesRoute: AuthenticatedAdminInquiriesRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdmissionsRouteChildren {
  AdmissionsCheckStatusRoute: typeof AdmissionsCheckStatusRoute
  AdmissionsIndexRoute: typeof AdmissionsIndexRoute
}

const AdmissionsRouteChildren: AdmissionsRouteChildren = {
  AdmissionsCheckStatusRoute: AdmissionsCheckStatusRoute,
  AdmissionsIndexRoute: AdmissionsIndexRoute,
}

const AdmissionsRouteWithChildren = AdmissionsRoute._addFileChildren(
  AdmissionsRouteChildren,
)

interface ApplyRouteChildren {
  ApplySuccessRoute: typeof ApplySuccessRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplySuccessRoute: ApplySuccessRoute,
  ApplyIndexRoute: ApplyIndexRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface PortalRouteChildren {
  PortalStudentRoute: typeof PortalStudentRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalStudentLoginRoute: typeof PortalStudentLoginRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalStudentRoute: PortalStudentRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalStudentLoginRoute: PortalStudentLoginRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRouteWithChildren,
  AlumniRoute: AlumniRoute,
  ApplyRoute: ApplyRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  MediaRoute: MediaRoute,
  NewsRoute: NewsRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  StaffRoute: StaffRoute,
  StudentLifeRoute: StudentLifeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
